.PHONY: clean All

All:
	@echo "----------Building project:[ MinimosQuadradospolinomiaisGrau2 - Debug ]----------"
	@cd "MinimosQuadradospolinomiaisGrau2" && "$(MAKE)" -f  "MinimosQuadradospolinomiaisGrau2.mk"
clean:
	@echo "----------Cleaning project:[ MinimosQuadradospolinomiaisGrau2 - Debug ]----------"
	@cd "MinimosQuadradospolinomiaisGrau2" && "$(MAKE)" -f  "MinimosQuadradospolinomiaisGrau2.mk" clean
