.PHONY: clean All

All:
	@echo "----------Building project:[ MinimosQuadradosLineares - Debug ]----------"
	@cd "MinimosQuadradosLineares" && "$(MAKE)" -f  "MinimosQuadradosLineares.mk"
clean:
	@echo "----------Cleaning project:[ MinimosQuadradosLineares - Debug ]----------"
	@cd "MinimosQuadradosLineares" && "$(MAKE)" -f  "MinimosQuadradosLineares.mk" clean
